### ISSUE TITLE
Error creating a table in redshift

### ISSUE THREAD

**Issue by drewspencerpearson** [agawronski/pandas_redshift#21] opened 2018-03-30 22:42 UTC
### Expected Behaviour
the pandas_to_redshift function successfully saves a pandas df in S3, then it should successfully create a table in redshift, but that is not the case. 

### Actual Behaviour
After successful creation of the csv in S3 the funtion pandas_to_redshift gives an error in the "CREATING A TABLE IN REDSHIFT" section. Specifically, "syntax error at or near "varchar" "

### Steps to reproduce (If possible)
a screen shot of the issue:

<img width="1041" alt="screen shot 2018-03-30 at 3 42 09 pm" src="https://user-images.githubusercontent.com/22479860/38156177-f1b40e2a-3430-11e8-986c-d9401cacf520.png">

**Comment by agawronski** [comment] 2018-03-31 14:06
Hi @drewspencerpearson. At a glance, it looks like your DataFrame has columns which contain spaces in the names. This is not a situation which is currently handled by pandas_redshift. Please leave this issue open, but for now a quick solution would be to remove or replace the the spaces in your column names before writing the DataFrame to redshift.

**Comment by agawronski** [comment] 2018-09-30 03:19
This is fixed as of release 1.1.3.

**Closed as completed by agawronski** 2018-09-30 03:19 UTC

**Comment by ynorouzz** [comment] 2020-02-21 11:59
I had the same issue with "." in column names in release 2.0.1. When I replaced the "." the issue is resolved.
